### ISSUE TITLE
Alias of h5 objects doesn't inherit class

### ISSUE THREAD

**Issue by ixxie** [mannau/h5#21] opened 2015-10-02 11:36 UTC
This might be a bug, and might be an intended functionality, but when using the arrow assignment twice in one line, h5 classes do not seem to be inherited.

This code demonstrates the problem:

    require('h5')
    file.remove("pickles.h5")
    file <- h5file(name="pickles.h5", mode='a')

    path <- "group/data"
    alias <- file[path] <- rnorm(23)

    print(file[path])
    print(alias)

*file[path]* will be an h5 object, while *alias* would be a vector object.

Note that an easy workaround is to split assignment to two lines:

    file[path] <- rnorm(23)
    alias <- file[path]

Thanks for this wonderful package!

**Comment by mannau** [comment] 2015-10-02 15:11
Interesting Question! 
That seems to be standard R-behaviour for multiple assignments in one line.
The rightmost gets assigned to all variables on the left:
```r
> test <- data.frame(a = rnorm(23), b = rnorm(23))
> val <- test["a"] <- test["b"] <- 1
> val
[1] 1
> head(test["a"])
  a
1 1
2 1
3 1
4 1
5 1
6 1
> head(test["b"])
  b
1 1
2 1
3 1
4 1
5 1
6 1
```
So, imho not a bug.
best,
m

**Closed by mannau** 2015-10-02 15:11 UTC
