### ISSUE TITLE
Support for 32-bit floats

### ISSUE THREAD

**Issue by weatherfrog** [mannau/h5#10] opened 2015-08-31 12:01 UTC
Hi,
Opening a 32-bit float dataset results in an error message:
```gnu-r
> f <- h5file("test.h5", "r")
> f["/dataset"]
Error: Datatype unknown.
```
The same dataset stored with 64-bits poses no problems. Is there a workaround for this?

**Comment by mannau** [comment] 2015-08-31 12:49
I just commited branch issue-10 to address this problem but couldn't reproduce it.
Using h5py I created a testfile as follows:
```python
import h5py
import numpy as np

f = h5py.File('test-f32.h5', 'a')
dset = f.create_dataset("floats", (100,), dtype='f32')
dset[0:99] = np.arange(99)
f.close()
```
and imported it in test case DataSet-Bug-F32:
```python
fname <- system.file("test-f32.h5", mustWork = TRUE)
file <- h5file(fname, "r")
expect_that(file["floats"][], is_identical_to(c(0:98, 0)))
h5close(file)
```
which works as expected.
Could you pls send me a file/code to check the issue and the output of sessionInfo() to see which version of h5 you are using?

**Comment by weatherfrog** [comment] 2015-09-02 09:01
Sorry for the delay. Here's an example that reproduces the issue. The h5 R library cannot read datasets stored with "big endian" byte-order (``>f4``).
```python
with h5py.File('test-f32.h5', 'w') as f:
    dset = f.create_dataset("floats", (3,), dtype='>f4')
    dst[:] = [1, 2, 3]
```
It works when you change the dtype to ``<f4`` (little endian). Note that little endian is the default on most PCs. But the file I was trying to read was produced by a supercomputer with a big endian architecture.

Can you imagine what the problem is? Since hdf5 is supposed to be endianness-agnostic, I would expect the hdf5 C-library to take care of this conversion.?

```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
[...]

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] h5_0.9.3
```

**Comment by mannau** [comment] 2015-09-02 18:04
Should be fixed now - thanks for reporting!

**Closed by mannau** 2015-09-02 18:04 UTC

**Comment by weatherfrog** [comment] 2015-09-02 20:30
You're welcome.
